version: "3.7"

services:
  godoc:
    image: godoc:1.0
    hostname: godoc
    container_name: godoc
    volumes:
      - sms:/home
    port:
      - 127.0.0.1:6060:6060
    network_mode: "host"
    command: /bin/sh -c "while :; do sleep 10; done"

volumes:
  sms:
    driver_opts:
      type: none
      device: # Path
      o: bind
